development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redistogo:55085fcda7b7d4e9d87a5313e347dcec@dory.redistogo.com:10300/" } %>
  channel_prefix: slack_chat_production
